package psh:profiling;

world bindings {
    import name: func() -> string;
    import op:system/version@0.0.0;
    import op:perf/counter@0.0.0;
    import op:memory/info@0.0.0;
    import op:cpu/info@0.0.0;
}
